#cloud-config
write_files:
  - path: /root/tayga.install.sh
    permissions: '0755'
    owner: root:root
    content: |
      ${nat64_script}


runcmd:
  - "bash /root/tayga.install.sh > /tmp/tayga.install.log 2>&1"